const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_QUEUED_CARDS: "STORE_QUEUED_CARDS",
   RESET_QUEUE: "RESET_QUEUE",
   INCREMENT_QUEUE_INDEX: "INCREMENT_QUEUE_INDEX",
   DECREMENT_QUEUE_INDEX: "DECREMENT_QUEUE_INDEX",
};

export default actions;
